version: "3.7"
services:
  app:
    build:
      args:
        user: huss
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cmrad
    container_name: cmrad-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cmrad

  db:
    image: mysql:5.7
    container_name: cmrad-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - cmrad

  nginx:
    image: nginx:alpine
    container_name: cmrad-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - cmrad

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: cmrad-phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST:db
      - MYSQL_USERNAME:huss
      - MYSQL_ROOT_PASSWORD:secret
    depends_on:
      - db
    networks:
      - cmrad
    volumes:
      - ./docker/phpmyadmin
networks:
  cmrad:
    driver: bridge
